version: "3.8"

services:
  ################
  ## API GAMING ##
  ################
  thegame_gaming_api:
    container_name: thegame_gaming_api
    image: node
    ports:
      - "3001:3000"
    volumes:
      - ./gaming_api:/app
    working_dir: /app
    env_file:
      - ./gaming_api/.env
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    #command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    # links:
    #   - thegame_gaming_db:mongo
    depends_on:
      - thegame_gaming_db
      - thegame_users_api

  thegame_gaming_db:
    container_name: thegame_gaming_db
    image: mongo
    volumes:
      - ./gaming_db_data/:/data/db
    ports:
      - 27018:27017
    env_file:
      - ./gaming_db/.env

  thegame_gaming_mongoexpress:
    container_name: thegame_gaming_mongoexpress
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./gaming_db/.env
    # links:
    #   - thegame_gaming_db:mongo
    depends_on:
      - thegame_gaming_db

  ###############
  ## API USERS ##
  ###############
  thegame_users_api:
    container_name: thegame_users_api
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./users_api:/app
    working_dir: /app
    env_file:
      - ./users_api/.env
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    #command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    depends_on:
      - thegame_users_db

  thegame_users_db:
    container_name: thegame_users_db
    image: mariadb
    env_file:
      - ./users_db/.env
    volumes:
      - ./users_db_data:/var/lib/mysql

  thegame_users_adminer:
    container_name: thegame_users_adminer
    image: adminer
    ports:
      - 9090:8080
    depends_on:
      - thegame_users_db

  ################
  ## API MAILER ##
  ################
  thegame_mailer_api:
    container_name: thegame_mailer_api
    image: node
    ports:
      - "3005:3000"
    volumes:
      - ./mailer_api:/app
    working_dir: /app
    env_file:
      - ./mailer_api/.env
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    #command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    depends_on:
      - thegame_mailer_maildev

  thegame_mailer_maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
