version: "3.8"

networks:
  thegame:
    driver: bridge

services:
  thegame.users.api:
    container_name: thegame.users.api
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./users_api:/app
      - ./users_api/node_modules:/app/outside/node_modules
    working_dir: /app
    env_file:
      - ./users_api/.env
    command: bash -c 'npm i && npm run dev'
    networks:
      - thegame
