version: "3.8"

services:
  ##################
  ## API E-GAMING ##
  ##################
  the_game_e_gaming_api:
    container_name: the_game_e_gaming_api
    image: node
    ports:
      - "3001:3000"
    volumes:
      - ./e_gaming_api:/app
    working_dir: /app
    env_file:
      - ./e_gaming_api/.env
    #command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    # links:
    #   - the_game_e_gaming_db:mongo
    depends_on:
      - the_game_e_gaming_db

  the_game_e_gaming_db:
    container_name: the_game_e_gaming_db
    image: mongo
    volumes:
      - ./e_gaming_db_data/:/data/db
    ports:
      - 27018:27017
    env_file:
      - ./e_gaming_db/.env

  the_game_e_gaming_mongoexpress:
    container_name: the_game_e_gaming_mongoexpress
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./e_gaming_mongoexpress/.env
    # links:
    #   - the_game_e_gaming_db:mongo
    # depends_on:
    #   - the_game_e_gaming_db

  ###############
  ## API USERS ##
  ###############
  the_game_users_api:
    container_name: the_game_users_api
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./users_api:/app
    working_dir: /app
    env_file:
      - ./users_api/.env
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    #command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    depends_on:
      - the_game_users_db

  the_game_users_db:
    container_name: the_game_users_db
    image: mariadb
    env_file:
      - ./users_db/.env
    volumes:
      - ./users_db_data:/var/lib/mysql

  the_game_users_adminer:
    container_name: the_game_users_adminer
    image: adminer
    ports:
      - 9090:8080

  ################
  ## API MAILER ##
  ################
  the_game_mailer_api:
    container_name: the_game_mailer_api
    image: node
    ports:
      - "3005:3000"
    volumes:
      - ./mailer_api:/app
    working_dir: /app
    env_file:
      - ./mailer_api/.env
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    #command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    depends_on:
      - the_game_mailer_maildev

  the_game_mailer_maildev:
    image: maildev/maildev
    ports:
      - "1080:80"

  #####################
  ## API BROADCASTER ##
  #####################
  the_game_broadcaster_api:
    container_name: the_game_broadcaster_api
    image: node
    ports:
      - "3004:3000"
    volumes:
      - ./broadcaster_api:/app
    working_dir: /app
    env_file:
      - ./broadcaster_api/.env
    #command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
  ################
  ## API MEDIAS ##
  ################
  the_game_medias_api:
    container_name: the_game_medias_api
    image: node
    ports:
      - "3003:3000"
    volumes:
      - ./medias_api:/app
    working_dir: /app
    env_file:
      - ./medias_api/.env
    #command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    depends_on:
      - the_game_medias_db
  the_game_medias_db:
    container_name: the_game_medias_db
    image: mariadb
    env_file:
      - ./medias_db/.env
    volumes:
      - ./medias_db_data:/var/lib/mysql
  ##################
  ## API GAMEPLAY ##
  ##################
  the_game_gameplay_api:
    container_name: the_game_gameplay_api
    image: node
    ports:
      - "3002:3000"
    volumes:
      - ./gameplay_api:/app
    working_dir: /app
    env_file:
      - ./gameplay_api/.env
    #command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment
    command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloaing in dev environment
    #command: npm start #for production environment
    depends_on:
      - the_game_gameplay_db
  the_game_gameplay_db:
    container_name: the_game_gameplay_db
    image: mariadb
    env_file:
      - ./gameplay_db/.env
    volumes:
      - ./gameplay_db_data:/var/lib/mysql
